#! /bin/sh

for file in `cat obslist`; do
  ls $file/*summ*.txt >> xtmplst
done

if (test -s xtmplst); then
   rm -f hetg_angles.txt letg_angles.txt

   for file in `cat xtmplst`; do
     if (grep -q "HETG" $file); then
       echo "$file" >> hetg_angles.txt
       grep "abs_start_time" $file >> hetg_angles.txt
       grep "heg_all_angle" $file >> hetg_angles.txt
       grep "meg_all_angle" $file >> hetg_angles.txt
     fi
     if (grep -q "LETG" $file); then
       echo "$file" >> letg_angles.txt
       grep "abs_start_time" $file >> letg_angles.txt
       grep "leg_all_angle" $file >> letg_angles.txt
     fi
   done
fi

rm -f xtmplst

#end
