#! /bin/sh

#  must change these parameters monthly
indir=/dsops/ap/sdp/cache/#YEAR_MON#_*/pcad
workdir=/data/mta4/www/DAILY/mta_pcad/ACA/#UMONYR#
root=#LMONYR#
datadir=$workdir/Data

#PATH="/bin:/usr/bin:/home/ascds/DS.release/bin:/usr/local/bin:/opt/local/bin"
PATH="/bin:/usr/bin:/home/ascds/DS.release/bin:/usr/local/bin:/opt/local/bin:$PATH"
export PATH
#LD_LIBRARY_PATH="/home/ascds/DS.release/lib:/home/ascds/DS.release/ots/lib:/soft/SYBASE_OSRV15.5/OCS-15_0/lib:/home/ascds/DS.release/otslib:/opt/X11R6/lib:/usr/lib64/alliance/lib"
LD_LIBRARY_PATH="/opt/X11R6/lib:/usr/lib64/alliance/lib:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH

if ( test ! -d $datadir ); then
  echo $datadir 'does not exist'
  exit
fi

/usr/bin/rm xtmpdone
# find acen fidpr gspr that have not been processed
ls $indir/*_acen1* | grep -v '_static_' > xtmplst
if (test -s xtmplst); then
   for file in `cat xtmplst`; do
     match=`echo $file | awk -F"/" '{ print $8 }'`
     if (test ! -s $datadir/$match); then
       cp $file $datadir
       echo $file >> xtmpdone
     fi
   done
fi

ls $indir/*_fidpr1* | grep -v '_static_' > xtmplst
if (test -s xtmplst); then
   for file in `cat xtmplst`; do
     match=`echo $file | awk -F"/" '{ print $8 }'`
     if (test ! -s $datadir/$match); then
       cp $file $datadir
       echo $file >> xtmpdone
     fi
   done
fi

ls $indir/*_gspr1* | grep -v '_static_' > xtmplst
if (test -s xtmplst); then
   for file in `cat xtmplst`; do
     match=`echo $file | awk -F"/" '{ print $8 }'`
     if (test ! -s $datadir/$match); then
       cp $file $datadir
       echo $file >> xtmpdone
     fi
   done
fi

#  Run pipeline
#if ( test -s xtmpdone ); then
  echo "Added the following files to" $datadir
  cat xtmpdone
  echo ""
  ls $datadir/*acen* > ${datadir}/${root}_ACACENT.lis
  ls $datadir/*fidpr* > ${datadir}/${root}_FIDPROPS.lis
  ls $datadir/*gspr* > ${datadir}/${root}_GSPROPS.lis
  #punlearn mta_trend_aca
  pset mta_trend_aca verbose=5
#  pset mta_trend_aca clean_outdir=0
  flt_run_pipe -i $datadir -o $workdir/Report -r $root -t mta_trend_aca.ped 2>/dev/null
  echo ""
  # bookkeeping
  ##/data/mta4/www/DAILY/mta_pcad/ACA/obslst $datadir $workdir/obslst
  ##/data/mta4/www/DAILY/mta_pcad/ACA/obscomp $workdir/obslst
#fi

#rm -f xtmp*

#end
